tmgmt.translator.settings.client:
  type: mapping
  mapping:
    auto_accept:
      type: boolean
      label: Automatically accept
    remote_url:
      type: string
      label: Remote URL of the provider.
    job_comment:
      type: string
      label:  Comment to pass to the remote translator service


